# This workflow builds a Java project with Maven, caches/restores dependencies to improve execution time,
# and deploys a Docker image.
# For more information, see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Project CI/CD Workflow

on:
  push:
    branches:
      - testgit

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build and test
        run: mvn clean package -DskipTests

  deploy-docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: GlueOps/github-actions-build-push-containers@v0.3.7
        with:
          registry: "docker.io"
          dockerhub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
