name: ci-cd pipeline

on:
  push:
    branches:
      - testgit

jobs:

  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - name: check-out the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        run: mvn clean package -DskipTests

  docker-image:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_USERNAME}}/kpisbackend:latest

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push image to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/kpisbackend:latest






