name: ci-cd pipeline

on:
  push:
    branches:
      - testgit

jobs:
  build-deploy:
    name: build and deploy spring app to docker
    runs-on: ubuntu-latest
    steps:
      - name: check-out the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Test
        run: mvn clean package -DskipTests


